build:
	gcc -Wall -Wextra -pedantic -std=c11 -pthread 00-introduction.c -o 00-introduction
	gcc -Wall -Wextra -pedantic -std=c11 -pthread 01-mutex.c -o 01-mutex
	gcc -Wall -Wextra -pedantic -std=c11 -pthread 02-bank.c -o 02-bank

clean:
	rm 00-introduction
	rm 01-mutex
	rm 02-bank