void init();
int get_input();
void game_end(int zombies);
void print_msg(char *msg) ;
void print_fail(char *msg);
void print_succ(char *msg);
void print_gold(int gold) ;
void print_soldiers(int soldiers);
void print_zombies(int distance, int zombies);
void print_health(int health);