build:
	gcc -Wall -Wextra -pedantic -std=c11 -pthread -pthread 00-introduction.c -o 00-introduction
	gcc -Wall -Wextra -pedantic -std=c11 -pthread -pthread 01-library.c -o 01-library

clean:
	rm 00-introduction
	rm 01-library
